# Generated by Django 5.2.7 on 2025-11-06 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_mesa_reserva_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas', to='reserva.reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reserva.mesa'),
        ),
    ]
